exports.LOCALBRAND_STATUS = {
	ACTIVE: "ACTIVE",
	INACTIVE: "INACTIVE",
	REQUEST: "REQUEST",
};

exports.PRODUCT_STATUS = {
	ACTIVE: "ACTIVE",
	INACTIVE: "INACTIVE",
};

exports.PRODUCT_TYPE = {
	GENERAL_PRODUCT: "GP",
	DETAIL_PRODUCT: "DP",
};

exports.CUSTOMER_STATUS = {
	ACTIVE: "ACTIVE",
	INACTIVE: "INACTIVE",
};

exports.CUSTOMER_GENDER = {
	MALE: "MALE",
	FEMALE: "FEMALE",
	OTHER: "OTHER",
};

exports.ORDERDETAIL_STATUS = {
	ACTIVE: "ACTIVE",
	INACTIVE: "INACTIVE",
};

exports.ORDER_STATUS = {
	RECEIVED: "RECEIVED",
	SHIPPING: "SHIPPING",
	COMPLETED: "COMPLETED",
	CANCELLED: "CANCELLED",
};

exports.SIZE_SPECS = {
	WEIGHT_MIN: 0,
	WEIGHT_MAX: 200,
	WEIGHT_DELTA: 5,
	HEIGHT_MIN: 0,
	HEIGHT_MAX: 250,
	HEIGHT_DELTA: 10,
	BUST_MIN: 0,
	BUST_MAX: 200,
	BUST_DELTA: 10,
	WAIST_MIN: 0,
	WAIST_MAX: 200,
	WAIST_DELTA: 10,
	HIP_MIN: 0,
	HIP_MAX: 200,
	HIP_DELTA: 10,
};
