exports.LOCALBRAND_STATUS = {
	ACTIVE: "ACTIVE",
	INACTIVE: "INACTIVE",
	REQUEST: "REQUEST",
};

exports.PRODUCT_STATUS = {
	ACTIVE: "ACTIVE",
	INACTIVE: "INACTIVE",
};

exports.PRODUCT_TYPE = {
	GENERAL_PRODUCT: "GP",
	DETAIL_PRODUCT: "DP",
};

exports.CUSTOMER_STATUS = {
	ACTIVE: "ACTIVE",
	INACTIVE: "INACTIVE",
};

exports.CUSTOMER_GENDER = {
	MALE: "MALE",
	FEMALE: "FEMALE",
	OTHER: "OTHER",
};

exports.ORDERDETAIL_STATUS = {
	ACTIVE: "ACTIVE",
	INACTIVE: "INACTIVE",
};

exports.ORDER_STATUS = {
	RECEIVED: "RECEIVED",
	SHIPPING: "SHIPPING",
	COMPLETED: "COMPLETED",
	CANCELLED: "CANCELLED",
};
