components:
  schemas:
    Product:
      type: "object"
      properties:
        id:
          type: "string"
          format: "uuid"
          description: The auto generate id of Localbrand
        brandId:
          type: "string"
          required: true
          format: "uuid"
          description: The Foreign key from Localbrand
        categoryId:
            type: string
            required: true
            format: uuid
            description: The Foreign key from Catgory
        thumbanailUrl:
            type: string
            required: true
            description: the Url of thumbnail Image
        name:
            type: string
            required: true
            description: the name of the Product
        description:
            type: string
            required: true
            description: the description of the product        
        status:
            type: string
            enum : ["ACTIVE", "INACTIVE"]
            description: the status of Localbrand
        price:
            type: number
            description: The price of product
            required: true
        color:
            type: string
            description: The color of the product
            required: true
        quantiy:
            type: number
            description: The quantity of product
            required: true
        parentId:
            type: string
            format: uuid
            description: the parents's product id of this product refer to
        size:
            type: string
            description: the size of the product
        type:
            type: string
            enum:  [GENERAL_PRODUCT , DETAIL_PRODUCT]
            description: the type of the product
            required: true
        timestamps:
            type: string
            format: date-time
            description: the time of this product create    
      example: 
        status: "ACTIVE"
        _id: "60b09f8c7904b66b746cca2c"
        brandId: "60ae5bbd1bca945ff4b5322d"
        type: "GP"
        description: "Áo thời trang mới nhất mùa hè 2021"
        name: "Áo thun tay lỡ"
        categoryId: "60ae5abe1bca945ff4b5321e"
        price: 524000
        color: "Black"
        quantity: 173
        hashtags: [
            {
                "_id": "60ae5a5c1bca945ff4b5320b",
                "name": "docdao"
            }
        ]
    

    ProductHashtag:
      type: object
      properties:
        id: 
          type: "string"
          description: The auto generate id of producthashtag
        productId: 
          type: "string"
          description: The id of product
        hashtagId: 
          type: "string"
          description: The id of hashtag
      
paths:
  /api/products/{id}: 
    get: 
      tags:
        - Product
      summary: Return product by id
      produces:
        - application/json
      parameters: 
        - name: id 
          in: path 
          type: "string"
          description: path parameter takes the product id
          required: true
      responses:
        '200':
          description: get product
          content:
            application/json:
              schema:
                type: object
                properties:
                  product:
                    $ref: "#/components/schemas/Product"
        '404':
          description: product not found
    delete:
      tags:
        - "Product"
      summary: "Delete a product by Id"
      parameters:
      - name: id
        in: path
        required: true
      responses:
        200:
          description: delete successfully
          content:
            application/json:
              schema:
                type: object
                $ref: "#/components/schemas/Product"
        500:
          description: Internal server error
    put:
      tags:
        - "Product"
      summary: "Modify a product"
      parameters:
      - name: id 
        in: path 
        type: "string"
        description: id of product 
        required: true
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/definitions/ProductReqBody"
      responses:
        200:
          description: add successfully
          content:
            application/json:
              schema:
                type: object
                $ref: "#/components/schemas/Product"
        500:
          description: Internal server error      

  /api/products/{id}/hashtags:
    get: 
      tags: [ProductHashtag]
      summary: Return Hashtags by product id
      produces:
        - application/json
      parameters: 
        - name: id 
          in: path 
          type: "string"
          description: path parameter takes the product id
          required: true
      responses:
        200:
          description: get hashtag
          content:
            application/json:
              schema:
                type: object
                properties:
                  hashtag:
                    type: array
                    items: 
                      $ref: "#/components/schemas/Hashtag"
        500:
          description: Internal server error
    post:
      summary: "Insert hashtag product"
      produces:
      - application/json
      parameters: 
        - name: productId 
          in: path 
          type: "string"
          description: path parameter takes the product id
          required: true
      tags: [ProductHashtag]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                hashtagId:
                  type: string
                  description: path parameter takes the product id
                  required: true  
      responses:
        200:
          description: the inserted category
          content:
            application/json:
              schema:
                type: object
                properties:
                  ProductHashtag:
                      $ref: '#/components/schemas/ProductHashtag'
        500:
          description: bad request
  /api/products/{id}/hashtags/{hashtagId}:
    delete:
      tags:
        - "ProductHashtag"
      summary: "Delete a hashtag of a product by hashtagId and productId"
      parameters:
      - name: id
        in: path
        required: true
      - name: hashtagId
        in: path
        required: true
      responses:
        200:
          description: the hashtag is deleted 
          content:
            application/json:
              schema:
                type: object
                properties:
                  ProductHashtag:
                    $ref: '#/components/schemas/ProductHashtag'
        500:
          description: Internal server error
  /api/products:
    get: 
      tags:
        - Product
      summary: Return Products by using filter
      produces:
        - application/json
      parameters: 
        - name: categoryId 
          in: query 
          type: "string"
          description: categoryId query string 
        - name: sort 
          in: query 
          type: "string"
          description: sort condition selected by user query string
        - name: queryValue 
          in: query 
          type: "string"
          description: search query value by user query string  
        - name: sizes 
          in: query 
          type: "string"
          description: sizes of products query string 
        - name: page 
          in: query 
          type: "string"
          description: pagination tracking query string 
        - name: brandIds 
          in: query 
          type: "string"
          description: brandId of the product
        - name: prices 
          in: query 
          type: number
          description: the price range of the product      
      responses:
        200:
          description: get product by conditions
          content:
            application/json:
              schema:
                type: object
                properties:
                  product:
                    type: array
                    items:
                      $ref: "#/definitions/ConditionalProduct"
        500:
          description: Internal server error
    post:
      tags:
        - "Product"
      summary: "Create a product"
      
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/definitions/ProductReqBody'   
      responses:
        200:
          description: create successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                    product:
                      $ref: "#/components/schemas/Product"
        500:
          description: Internal server error

 
    



definitions: # Schema definition for the request body
  ConditionalProduct:
    type: object
    properties:
      products:
        type: array
        items:
          $ref: '#/components/schemas/Product'
      totalItems:
        type: integer
        description: The total items of search values
      limit:
        type: integer
        description: The limit items on each page
      totalPages:
        type: integer
        description: The total pages
      page:
        type: integer
        description: the current page
      pagingCounter:
        type: integer
        description: The counter for tracking page
      hasPrevPage:
        type: boolean
        description: The boolean value for checking page has prev or not
      hasNextPage:
        type: boolean
        description: The boolean value for checking page has next or not
      prevPage:
        type: integer
        description: total pages before
      nextPage:
        type: integer
        description: total pages left
  ProductReqBody:
    description: A Json object contain product's OrderData
    type: object
    properties:
      name:
        type: string
        required: true
        description: the name of the Product
      description:
        type: string
        required: true
        description: the description of the product        
      status:
        type: string
        enum : ["ACTIVE", "INACTIVE"]
        description: the status of Localbrand
      price:
        type: number
        description: The price of product
        required: true
      color:
        type: string
        description: The color of the product
        required: true
      quantiy:
        type: number
        description: The quantity of product
        required: true
      parentId:
        type: string
        format: uuid
        description: the parents's product id of this product refer to
      size:
        type: string
        description: the size of the product
      type:
        type: string
        enum:  ["GENERAL_PRODUCT" , "DETAIL_PRODUCT"]
        description: the type of the product
        required: true


      

